# Generated by Django 4.1 on 2022-11-22 02:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_promo', models.CharField(max_length=15)),
                ('diskon', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=100)])),
                ('tipe_promo', models.CharField(choices=[('m', 'Min Transaksi'), ('h', 'Hari Spesial')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PromoHariSpesial',
            fields=[
                ('promo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riwayat_dan_promo.promo')),
                ('tanggal_spesial', models.DateField()),
            ],
            bases=('riwayat_dan_promo.promo',),
        ),
        migrations.CreateModel(
            name='PromoMinTransaksi',
            fields=[
                ('promo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riwayat_dan_promo.promo')),
                ('min_transaksi', models.IntegerField()),
            ],
            bases=('riwayat_dan_promo.promo',),
        ),
    ]
