# Generated by Django 4.1 on 2022-11-23 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sirest_b09', '0009_remove_makanan_category_remove_makanan_rname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriMakanan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kategorimakanan.kategorimakanan')),
                ('rname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sirest_b09.restoran')),
            ],
        ),
    ]
