# Generated by Django 4.1 on 2022-11-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategorimakanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorimakanan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
