# Generated by Django 4.0.4 on 2022-11-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirest_b09', '0003_alter_kurir_sim_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurir',
            name='no_rek',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='kurir',
            name='sim_num',
            field=models.CharField(max_length=18),
        ),
    ]
