# Generated by Django 4.0.4 on 2022-11-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirest_b09', '0004_alter_kurir_no_rek_alter_kurir_sim_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurir',
            name='trans_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
