# Generated by Django 4.0.4 on 2022-11-20 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirest_b09', '0005_kurir_trans_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelanggan',
            old_name='nama',
            new_name='name',
        ),
    ]
