# Generated by Django 4.0.4 on 2022-11-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirest_b09', '0006_rename_nama_pelanggan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurir',
            name='trans_type',
            field=models.CharField(blank=True, choices=[('m', 'Motor'), ('c', 'Mobil')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='gender',
            field=models.CharField(choices=[('p', 'Pria'), ('w', 'Wanita')], max_length=10),
        ),
    ]
