# Generated by Django 4.1 on 2022-11-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirest_b09', '0008_kategorimakanan_makanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makanan',
            name='category',
        ),
        migrations.RemoveField(
            model_name='makanan',
            name='rname',
        ),
        migrations.DeleteModel(
            name='KategoriMakanan',
        ),
        migrations.DeleteModel(
            name='Makanan',
        ),
    ]
