# Generated by Django 4.1.2 on 2022-11-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirest_b09', '0008_kategorimakanan_kategorirestoran_makanan_and_more'),
        ('sirest_b09', '0009_remove_makanan_category_remove_makanan_rname_and_more'),
    ]

    operations = [
    ]
