# Generated by Django 4.1.2 on 2022-11-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirest_b09', '0010_merge_20221123_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Makanan',
        ),
    ]
