# Generated by Django 4.1.2 on 2022-11-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirest_b09', '0011_delete_makanan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KategoriMakanan',
        ),
    ]
