# Generated by Django 4.1.2 on 2022-11-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirest_b09', '0013_kategorimakanan_makanan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakananCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sirest_b09.kategorimakanan')),
                ('rname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sirest_b09.restoran')),
            ],
        ),
        migrations.DeleteModel(
            name='Makanan',
        ),
    ]
