# Generated by Django 4.1.2 on 2022-11-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirest_b09', '0014_makanancustom_delete_makanan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MakananCustom',
            new_name='Makanan',
        ),
    ]
